global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:8888']  # 更新為 celery-exporter 服務

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']  # RabbitMQ Prometheus metrics endpoint

  # 一般系統監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']